Announcements/Announcements/Controllers/AnnouncementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Announcements.Services;
using AnnouncementsApp.Domain;
using AnnouncementsApp.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Announcements.Controllers
{
    public class AnnouncementsController : Controller
    {
        private readonly IUnitOfWork _uitOfWork;
        private readonly IUserService _userService;

        public AnnouncementsController(IUnitOfWork unitOfWork, IUserService userService)
        {
            _uitOfWork = unitOfWork;
            _userService = userService;
        }

        [Authorize]
        public IActionResult Index()
        {
            var announcements = _uitOfWork.Announcements.GetAll();
            return View(announcements);
        }

        [Authorize]
        public IActionResult Create()
        {
            Announcement vm = new Announcement();

            return View(vm);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Announcement announcement)
        {
            if (ModelState.IsValid)
            {
                announcement.Owner = _userService.GetSignedInUser();
                _uitOfWork.Announcements.Insert(announcement);
                _uitOfWork.Complete();
                return RedirectToAction(nameof(Index));
            }
            return View(announcement);
        }
        
        [Authorize]
        public IActionResult Delete(int id)
        {
            var announcement = _uitOfWork.Announcements.GetById(id);
            if (announcement == null)
            {
                return NotFound();
            }

            return View(announcement);
        }
        
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var announcement = _uitOfWork.Announcements.GetById(id);
            bool admin = await _userService.IsAdmin();
            
            
            if (admin)
            {
                _uitOfWork.Announcements.Delete(announcement);
                _uitOfWork.Complete();
            } else
            {
                var signedInUser = _userService.GetSignedInUser();
                if (announcement.Owner == signedInUser)
                {
                    _uitOfWork.Announcements.Delete(announcement);
                    _uitOfWork.Complete();
                }
            }            

            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        [HttpGet]
        [Route("Announcements/Edit/{id}", Name = "EditAnnouncements")]
        public IActionResult Edit(int id)
        {
            var announcement = _uitOfWork.Announcements.GetById(id);
            var signedInUser = _userService.GetSignedInUser();
            if (announcement.Owner == signedInUser)
            {
                return View();
            }

            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Announcements/Edit")]
        public IActionResult Edit(Announcement announcement)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(announcement);
        }

        [Authorize]
        public IActionResult Details(int id)
        {
            if (id == 0)
            {
                return RedirectToAction("Index");
            }
            else
            {
                var vm = new Announcement();

                vm = _uitOfWork.Announcements.GetById(id);

                return View(vm);
            }
        }

    }
}

Announcements/Announcements/Views/Announcements/Create.cshtml
@model AnnouncementsApp.Domain.Announcement

@{
    ViewData["Title"] = "Create";
}

<link rel="stylesheet" href="~/css/autocompleteControl.css">

<h2>Create</h2>
<h4>Announcement</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Announcements" asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CreateDate" class="control-label"></label>
                <input asp-for="CreateDate" class="form-control" type="date" />
                <span asp-validation-for="CreateDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ExpireDate" class="control-label"></label>
                <input asp-for="ExpireDate" class="form-control" type="date" />
                <span asp-validation-for="ExpireDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Category.Name" class="control-label">Category</label>
                <input asp-for="Category.Name" class="form-control" />
                <span asp-validation-for="Category.Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>

        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>
<script type="text/javascript" src="~/js/autocompleteControl.js"></script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Announcements/Announcements/Views/Announcements/Delete.cshtml
@model AnnouncementsApp.Domain.Announcement
@{
    ViewData["Title"] = "Delete";
}
<h2>Delete</h2>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Announcement</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Announcements/Announcements/Views/Announcements/Details.cshtml
@model AnnouncementsApp.Domain.Announcement

<div class="row">

    <!-- Blog Post Content Column -->
    <div class="col-lg-8">

        <!-- Blog Post -->
        <!-- Title -->
        <h1>
            <c:out value="@Model.Title" />
        </h1>

        <!-- Author -->
        @*<p class="lead">
            by <a href="#">@Model.Owner.FirstName &nbsp;@Model.Owner.LastName</a>
        </p>*@

        <hr>

        <!-- Date/Time -->
        <p>
            <span class="glyphicon glyphicon-time"></span>
            @Model.CreateDate
        </p>

        <hr>

        <!-- Preview Image -->
        <img class="img-responsive" src="http://placehold.it/900x300" alt="">

        <hr>

        <!-- Post Content -->
        <p class="lead">Category: @Model.Category.Name</p>
        <p class="lead">
            Category description:
            @Model.Category.Descriprion
        </p>
        <p class="lead">Location:@Model.Location</p>
        <p class="lead">Announcement content:@Model.Content</p>
        @*<p>Owner Email: @Model.Owner.Email</p>*@
        @*<p>Owner Phone: @Model.Owner.Phone</p>
        <p>Confirmation Code: ${announcement.confirmationCode}</p>*@
        <p>
            Expires on: <span class="glyphicon glyphicon-time"></span>
            @Model.ExpireDate
        </p>
        <hr>




        <!-- Comments Form -->
        <div class="well">
            <h4>Leave a Comment:</h4>
            <form:form action="/comments/add.do?aId=${announcement.id}" method="POST"
                       modelAttribute="newComment">
                <table>
                    <tr>
                        <td>Nane :</td>
                        <td><form:input type="text" path="name" /></td>
                    </tr>
                    <tr>
                        <td>Content :</td>
                        <!--  	<td><form:input type="text" path="content" /></td>-->
                        <td><form:textarea type="text" path="content" /></td>
                    </tr>
                    <tr>
                        <td colspan="2"><input type="submit" class="btn btn-primary" value="Submit"></td>
                    </tr>
                </table>
            </form:form>
        </div>

        <hr>



        <a class="btn btn-primary" href="/comments?id=${announcement.id}">
            Show
            Comments<span class="glyphicon glyphicon-chevron-right"></span>
        </a> <br />
        <br />

        <div class="well">
            <c:forEach var="X" items="${comments}">
                <c:set var="node" value="${X}" scope="request" />
                <jsp:include page="comment1.jsp" />
            </c:forEach>
        </div>


    </div>

    <!-- Blog Sidebar Widgets Column -->
    <div class="col-md-4">

        <!-- Blog Search Well -->
        <div class="well">
            <h4>Search Announcement</h4>
            <div class="input-group">
                <input type="text" class="form-control"> <span class="input-group-btn">
                    <button class="btn btn-default" type="button">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </span>
            </div>
            <!-- /.input-group -->
        </div>

        <!-- Blog Categories Well -->
        <!-- Side Widget Well -->
        <div class="well">
            <h4>Announcements website</h4>
            <p> This is a website for announcements</p>
        </div>

    </div>

</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Announcements/Announcements/Views/Announcements/Edit.cshtml
@model AnnouncementsApp.Domain.Announcement

@{
    ViewData["Title"] = "Create";
}

<link rel="stylesheet" href="~/css/autocompleteControl.css">

<h2>Edit</h2>
<h4>Announcement</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Announcements" asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <input asp-for="Content" class="form-control" />
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CreateDate" class="control-label"></label>
                <input asp-for="CreateDate" class="form-control" type="date" />
                <span asp-validation-for="CreateDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ExpireDate" class="control-label"></label>
                <input asp-for="ExpireDate" class="form-control" type="date" />
                <span asp-validation-for="ExpireDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Category.Name" class="control-label"></label>
                <input asp-for="Category.Name" class="form-control" />
                <span asp-validation-for="Category.Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>

        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>
<script type="text/javascript" src="~/js/autocompleteControl.js"></script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Announcements/Announcements/Views/Announcements/Index.cshtml
@model IEnumerable<AnnouncementsApp.Domain.Announcement>

@{
    ViewData["Title"] = "Announcements";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Title
            </th>
            <th>
                Category
            </th>
            <th>
                Owner
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Owner.FirstName)
                    @Html.DisplayFor(modelItem => item.Owner.LastName)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-route="EditAnnouncements" asp-route-id="@item.Id">Edit</a>
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>


                </td>
            </tr>
        }
    </tbody>
</table>